on:
  push:
    branches:
      - main
      
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action
      - name: Checkout Repo
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - name: Setupt Node.js 16.x 
        uses: actions/setup-node@v3
        with:
          node-version: 16
        if: ${{ steps.release.outputs.release_created }}
      - name: Install Dependencies 
        run: npm install
        if: ${{ steps.release.outputs.release_created }}
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN_FLOWBITE
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_FLOWBITE }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Create a package and Publish to npm 
        run: npm run package
        if: ${{ steps.release.outputs.release_created }}
      - name: Change dir
        run: cd package
        if: ${{ steps.release.outputs.release_created }}
      - name: Run npm publish
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_FLOWBITE }}
        if: ${{ steps.release.outputs.release_created }}